### ISSUE TITLE
Motivating Examples clarification 

### ISSUE THREAD

**Issue by Fishrock123** [GeoffreyBooth/node-import-file-specifier-resolution-proposal#2] opened 2018-11-21 22:46 UTC
The Motivating Examples section uses the term "project", which I'm not sure is well specified.

Does project mean "all local non-module code in a project", or "all source code loaded by a project"?

Specifically, I believe that this stated case is perhaps impossibly rare in the latter case:

> A project where all source is a transpiled language such as TypeScript or CoffeeScript.

**Comment by GeoffreyBooth** [comment] 2018-11-21 23:02
By “project” I mean a folder that has source code files in it. So if I create a new folder and run `npm init` in it, and then create source files in it, that’s a project. https://github.com/GeoffreyBooth/node-import-file-specifier-resolution-proposal/tree/master/esm-npm-modules-research is a project, and its subfolder is another project.

Basically a project is the same as a package, but not necessarily intended to ever be imported by something else the way a package is. So if I use `create-react-app` to create a new project, that’s intended to be an app that runs and imports dependencies, but isn’t itself intended to ever be imported as a dependency.

Both TypeScript and CoffeeScript support `import` and `export` statements, and so can be transpiled into ESM JavaScript. The issue is that both projects currently output ESM with `.js` extensions, and there are entire ecosystems dependent on that behavior, and so requiring an `.mjs` extension would be very disruptive to those communities.

**Comment by Fishrock123** [comment] 2018-11-22 01:55
Sorry, to clarify:

Are dependencies included in this definition fo what is "in" a project?

**Comment by GeoffreyBooth** [comment] 2018-11-26 07:08
> Are dependencies included in this definition fo what is “in” a project?

No. Just as people generally `.gitignore` their `node_modules` folder, I’m referring to the files that a user is working on, not all dependencies that they may have `npm install`ed into their `node_modules` subfolder. If you look at https://github.com/GeoffreyBooth/node-import-file-specifier-resolution-proposal/tree/master/esm-npm-modules-research, there are no dependencies committed there; the files that I’ve committed are what I consider to be the project.

I’m not sure that this needs to be much more specific, as this isn’t part of the proposal. It’s just a list of examples explaining our motivations for why we made the central decision of looking at package scope for how Node should determine how to parse JavaScript files. The following section gets into more detail about that.

**Closed by GeoffreyBooth** 2018-11-26 07:08 UTC
